// Auto-generated by ui-autotest skill — DO NOT EDIT MANUALLY
// Feature: 【数据质量】菜单名称修改
// Type: 完整回归 (P0+P1+P2)
// Generated: 2026-04-04

import { test, expect } from '@playwright/test'

type FailedRequest = {
  url: string
  method: string
  status: number
  requestHeaders: Record<string, string>
  requestBody: string
  responseBody: string
}

/** 验证菜单名称修改后的预期列表 */
const EXPECTED_MENUS = [
  '总览',
  '规则库配置',
  '规则集管理',
  '规则任务管理',
  '校验结果查询',
  '数据质量报告',
  '通用配置',
  '项目管理',
]

/** 需求中明确要求验证的菜单名称变更 */
const RENAMED_MENUS = {
  '总览': '原名【概览】→ 改为【总览】',
  '规则任务管理': '原名【规则任务配置】→ 改为【规则任务管理】',
  '校验结果查询': '原名【任务实例查询】→ 改为【校验结果查询】',
  '数据质量报告': '原名【质量报告】→ 改为【数据质量报告】',
  '规则集管理': '新增一级菜单【规则集管理】',
}

test('【P2】验证新建项目菜单名称正确修改', async ({ page }) => {
  // ── 网络监听 ──────────────────────────────────────────────
  const failedRequests: FailedRequest[] = []
  page.on('response', async response => {
    if (response.status() >= 400) {
      let responseBody = ''
      try { responseBody = await response.text() } catch { /* ignore */ }
      failedRequests.push({
        url: response.url(),
        method: response.request().method(),
        status: response.status(),
        requestHeaders: response.request().headers(),
        requestBody: response.request().postData() ?? '',
        responseBody,
      })
    }
  })

  // ── 步骤 1: 进入数据资产 → 数据质量页面 ───────────────────
  await page.goto('http://shuzhan63-test-ltqc.k8s.dtstack.cn/dataAssets/#/dq/overview')
  await page.waitForLoadState('networkidle')

  // ── 步骤 2: 进入项目管理页面新建项目 ───────────────────────
  await page.getByRole('menuitem', { name: '项目管理' }).click()
  await page.waitForLoadState('networkidle')

  // 新建项目（若页面有新建按钮）
  const createBtn = page.getByRole('button', { name: /新建/ })
  if (await createBtn.count() > 0) {
    await createBtn.click()
    await page.waitForLoadState('networkidle')

    // 填写项目名称
    const nameInput = page.getByPlaceholder(/项目名称|请输入/)
    if (await nameInput.count() > 0) {
      await nameInput.fill(`autotest-${Date.now()}`)
    }

    // 点击确定/保存
    const confirmBtn = page.getByRole('button', { name: /确定|保存|提交/ })
    if (await confirmBtn.count() > 0) {
      await confirmBtn.click()
      await page.waitForLoadState('networkidle')
    }
  }

  // 切换到项目，通过点击项目选择器的文本区域
  const projectLabel = page.locator('.ant-select-selection-item').first()
  if (await projectLabel.count() > 0) {
    await projectLabel.click()
    await page.waitForTimeout(500)
    // 选择列表中的第一个选项（如果下拉打开了）
    const firstOption = page.locator('.ant-select-item-option').first()
    if (await firstOption.count() > 0) {
      await firstOption.click()
      await page.waitForLoadState('networkidle')
    }
  }

  // ── 步骤 3: 验证菜单名称 ─────────────────────────────────
  const sidebar = page.locator('aside, nav, [class*="sidebar"], [class*="sider"]').or(page.getByRole('complementary'))

  for (const [menuName, description] of Object.entries(RENAMED_MENUS)) {
    const menuItem = sidebar.getByRole('menuitem', { name: menuName })
    await expect(menuItem, `${description}`).toBeVisible({ timeout: 5000 })
  }

  // 验证完整菜单列表
  for (const expectedMenu of EXPECTED_MENUS) {
    const menuItem = sidebar.getByRole('menuitem', { name: expectedMenu })
    await expect(menuItem, `侧边栏应包含菜单「${expectedMenu}」`).toBeVisible({ timeout: 5000 })
  }

  // ── 失败请求上报 ──────────────────────────────────────────
  if (failedRequests.length > 0) {
    console.error('FAILED_API_REQUESTS:' + JSON.stringify(failedRequests))
  }
})

test('【P1】验证历史项目菜单名称正确修改', async ({ page }) => {
  // ── 网络监听 ──────────────────────────────────────────────
  const failedRequests: FailedRequest[] = []
  page.on('response', async response => {
    if (response.status() >= 400) {
      let responseBody = ''
      try { responseBody = await response.text() } catch { /* ignore */ }
      failedRequests.push({
        url: response.url(),
        method: response.request().method(),
        status: response.status(),
        requestHeaders: response.request().headers(),
        requestBody: response.request().postData() ?? '',
        responseBody,
      })
    }
  })

  // ── 步骤 1: 进入数据资产 → 数据质量页面 ───────────────────
  await page.goto('http://shuzhan63-test-ltqc.k8s.dtstack.cn/dataAssets/#/dq/overview')
  await page.waitForLoadState('networkidle')

  // ── 步骤 2: 验证历史项目下的菜单名称 ─────────────────────
  // 数据质量页面加载后，左侧菜单应直接可见（当前项目即为历史项目）
  const sidebar = page.locator('aside, nav, [class*="sidebar"], [class*="sider"]').or(page.getByRole('complementary'))

  // 验证 5 项菜单名称变更
  await expect(
    sidebar.getByRole('menuitem', { name: '总览' }),
    '【概览】应已改为【总览】'
  ).toBeVisible({ timeout: 5000 })

  await expect(
    sidebar.getByRole('menuitem', { name: '规则任务管理' }),
    '【规则任务配置】应已改为【规则任务管理】'
  ).toBeVisible({ timeout: 5000 })

  await expect(
    sidebar.getByRole('menuitem', { name: '校验结果查询' }),
    '【任务实例查询】应已改为【校验结果查询】'
  ).toBeVisible({ timeout: 5000 })

  await expect(
    sidebar.getByRole('menuitem', { name: '数据质量报告' }),
    '【质量报告】应已改为【数据质量报告】'
  ).toBeVisible({ timeout: 5000 })

  await expect(
    sidebar.getByRole('menuitem', { name: '规则集管理' }),
    '应新增一级菜单【规则集管理】'
  ).toBeVisible({ timeout: 5000 })

  // 验证完整菜单列表顺序
  for (const expectedMenu of EXPECTED_MENUS) {
    await expect(
      sidebar.getByRole('menuitem', { name: expectedMenu }),
      `侧边栏应包含菜单「${expectedMenu}」`
    ).toBeVisible({ timeout: 5000 })
  }

  // 验证旧名称不再存在
  const deprecatedMenus = ['概览', '规则任务配置', '任务实例查询', '质量报告']
  for (const oldName of deprecatedMenus) {
    await expect(
      sidebar.getByRole('menuitem', { name: oldName, exact: true }),
      `旧菜单名「${oldName}」应已不存在`
    ).not.toBeVisible({ timeout: 3000 })
  }

  // ── 失败请求上报 ──────────────────────────────────────────
  if (failedRequests.length > 0) {
    console.error('FAILED_API_REQUESTS:' + JSON.stringify(failedRequests))
  }
})
