// Auto-generated by ui-autotest skill — DO NOT EDIT MANUALLY
// Feature: 【数据质量】菜单名称修改
// Type: 冒烟测试 (P0)
// Generated: 2026-04-04
// Note: 本需求无 P0 用例，冒烟脚本为空

import { test } from '@playwright/test'

type FailedRequest = {
  url: string
  method: string
  status: number
  requestHeaders: Record<string, string>
  requestBody: string
  responseBody: string
}
