export const VERSION = "0.1.0";
export { execSql } from "./sdk/exec-sql";
export type { ExecSqlOptions } from "./sdk/exec-sql";
export { pingSql } from "./sdk/ping-sql";
export type { PingSqlOptions } from "./sdk/ping-sql";
export { precondSetup } from "./sdk/precond-setup";
export type { PrecondSetupOptions, PrecondSetupResult, PrecondTable } from "./sdk/precond-setup";
export { login, whoami, logout, getSession } from "./sdk/auth";
export type { LoginOptions } from "./sdk/auth";
export { ensureProject } from "./sdk/ensure-project";
export type { EnsureProjectOptions } from "./sdk/ensure-project";
export type { Session } from "./core/auth/login";
export type { Project } from "./core/platform/project";
export type { DtStackClientLike } from "./core/http/client";
