DROP TABLE IF EXISTS wwz_001;
DROP TABLE IF EXISTS wwz_002;
DROP TABLE IF EXISTS wwz_003;

CREATE TABLE wwz_001 (
    id INT COMMENT '用户ID',
    name VARCHAR(50) COMMENT '用户姓名'
) DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES ("replication_num" = "1");

CREATE TABLE wwz_002 (
    id INT COMMENT '用户ID',
    name VARCHAR(50) COMMENT '用户姓名'
) DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES ("replication_num" = "1");

CREATE TABLE wwz_003 (
    id INT COMMENT '用户ID',
    name VARCHAR(50) COMMENT '用户姓名'
) DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES ("replication_num" = "1");

INSERT INTO wwz_001 SELECT id, name FROM wwz_002;
INSERT INTO wwz_001 SELECT * FROM wwz_002 UNION ALL SELECT * FROM wwz_003
